### ISSUE TITLE
Delete Emoji

### ISSUE THREAD

**Issue by meliornox** [Valerokai/gssp_experiments#1]
The message generated by gssp_experiments says "To delete, someone click the "oof"" but it reacts with the "X" emoji, not the "oof" emoji.

**Comment by Valerokai** [comment]
Yeah, this issue is a thing with how the :oof: is hardcoded in
`strings.json`, and I kind of lowkey broke how it checks for the emoji + if
you run it on your own server, the emoji ID will obviously change.

I've added this as a bug on trello, and I'm going to work on making it so
it will autoformat the string with the name of the chosen emoji, or if the
emoji isn't avaliable, just the "X" emoji, and there should be a patch by
some point tonight

**Comment by valknight** [comment]
Yeah, this issue is a thing with how the :oof: is hardcoded in
`strings.json`, and I kind of lowkey broke how it checks for the emoji + if
you run it on your own server, the emoji ID will obviously change.

I've added this as a bug on trello, and I'm going to work on making it so
it will autoformat the string with the name of the chosen emoji, or if the
emoji isn't avaliable, just the "X" emoji, and there should be a patch by
some point tonight

**Comment by valknight** [comment]
Should be fixed in latest commit- can you confirm if the bug is still present?
